services:
  - type: web
    name: fake-user-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_HOST
        fromDatabase:
          name: fake-users-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: fake-users-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: fake-users-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: fake-users-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fake-users-db
          property: password

databases:
  - name: fake-users-db
    databaseName: fake_users_db
    plan: free
